name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: alss03
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, community, repositories, metadata
          
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          
          plugin_isocalendar: yes
          plugin_stars: yes
